cloudProvider: aws

autoDiscovery:
  clusterName: cgc-cluster   # ğŸ‘‰ EKS í´ëŸ¬ìŠ¤í„° ì´ë¦„ ì •í™•íˆ!

awsRegion: ap-northeast-2

rbac:
  serviceAccount:
    create: false            # ğŸ‘‰ ì´ë¯¸ ë§Œë“  ì„œë¹„ìŠ¤ì–´ì¹´ìš´íŠ¸ ì‚¬ìš©
    name: cluster-autoscaler # ğŸ‘‰ OIDC ì—°ë™ëœ SA ì´ë¦„ê³¼ ë™ì¼í•´ì•¼ í•¨

extraArgs:
  expander: least-waste
  balance-similar-node-groups: true
  skip-nodes-with-system-pods: false
  skip-nodes-with-local-storage: false
